name: Func Deploy
"on":
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Kubernetes context
        uses: azure/k8s-set-context@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          method: kubeconfig
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.REGISTRY_PASSWORD }}
          registry: ${{ vars.REGISTRY_LOGIN_URL }}
          username: ${{ vars.REGISTRY_USERNAME }}
      - name: Install func cli
        uses: gauron99/knative-func-action@main
        with:
          name: func
          version: knative-v1.19.1
      - name: Deploy function
        run: func deploy --registry=${{ vars.REGISTRY_LOGIN_URL }}/${{ vars.REGISTRY_USERNAME }} -v
