name: Remote Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: 1. Checkout code
      uses: actions/checkout@v4

    - name: 2. Setup Kubernetes context
      uses: azure/k8s-set-context@v4
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: 3. Login to container registry
      if: ${{ vars.USE_REGISTRY_AUTH == 'true' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY_HOST }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 4. Install func cli
      uses: gauron99/knative-func-action@main
      with:
        version: knative-v1.19.1
        name: func

    - name: 5. Deploy function
      run: func deploy --remote --registry=${{ vars.NAMESPACED_REGISTRY_URL }} -v